<?php

namespace Modules\Platform\Companies\Repositories;

use Modules\Platform\Companies\Entities\Company;
use Modules\Platform\Core\Repositories\PlatformRepository;


/**
 * Class CompanyRepository
 * @package Modules\Platform\Companies\Repositories
 */
class CompanyRepository extends PlatformRepository
{
    public function model()
    {
        return Company::class;
    }

    public function update(array $attributes, $id)
    {
        if ($attributes['user_limit'] == '') {
            $attributes['user_limit'] = null;
        }

        if ($attributes['storage_limit'] == '') {
            $attributes['storage_limit'] = null;
        }


        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function create(array $attributes)
    {
        if ($attributes['user_limit'] == '') {
            $attributes['user_limit'] = null;
        }

        if ($attributes['storage_limit'] == '') {
            $attributes['storage_limit'] = null;
        }


        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
