<?php

namespace Modules\Platform\Core\Fields;

use Kris\LaravelFormBuilder\Fields\FormField;
use Kris\LaravelFormBuilder\Form;
use Modules\Platform\Core\Helper\UserHelper;

/**
 * Class TagsType
 * @package Modules\Platform\Core\Fields
 */
class TagsType extends FormField
{

    protected $type = 'text';

    protected function getTemplate()
    {

        return 'vendor.laravel-form-builder.tags';
    }

    public function render(array $options = [], $showLabel = true, $showField = true, $showError = true)
    {
        $options['attr']['data-role'] = "tagsinput";



        return parent::render($options, $showLabel, $showField, $showError); // TODO: Change the autogenerated stub
    }

    public function getDefaults()
    {

        return parent::getDefaults(); // TODO: Change the autogenerated stub
    }

}
